### PR TITLE
Allow overriding span name by request attribute

### PR DESCRIPTION
**Pull request by ybasket**
To make interop with HTTP libraries like smithy4s easier, allow overriding the span name through a request attribute. This works very similar to the existing `ExtraAttributesKey`.

### CODE REVIEW

**Review by iRevive — APPROVED** [review]
Looks good.

**Review by NthPortal — APPROVED** [review]

**Comment by NthPortal** [comment]
@ybasket merge conflicts (with another of your PRs I think?), sorry 😬

**Comment by ybasket** [comment]
> @ybasket merge conflicts (with another of your PRs I think?), sorry 😬

No worries, was easy to resolve :)

**Comment by NthPortal** [comment]
thanks for the contributions!

**Pull request merged**
