### PR TITLE
Bump otel4s 0.11.0 and cats-effect 3.5.5

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Fix #147 by bumping cats-effect version.

### CODE REVIEW

**Comment by iRevive** [comment]
@NthPortal could we merge these changes and have a new release, please? RC should be enough.

**Comment by NthPortal** [comment]
as soon as the build passes I'll merge, pull locally and release

**Comment by NthPortal** [comment]
tagged and pushed as v0.10.0; publish job [here](https://github.com/http4s/http4s-otel4s-middleware/actions/runs/11723837710)

**Comment by iRevive** [comment]
Thanks @NthPortal!

**Pull request merged**
